### ISSUE TITLE
Follow the latest update of embeddedRTPS

### ISSUE THREAD

**Issue by takasehideki** [embedded-software-laboratory/embeddedRTPS-STM32#11]
This repository refers [embeddedRTPS @dc5e510 (Commits on Jan 14, 2020)](https://github.com/embedded-software-laboratory/embeddedRTPS/tree/dc5e5106b136e91fad54dc969f3a4d68ea101566) as the submodule. There are many important updates to embeddedRTPS recently, so we need to update this repository to be followed.
https://github.com/embedded-software-laboratory/embeddedRTPS/commits/master

This is a note to myself, requested by Alex @akampmann 
Since we are using this repository for our activity, we would like to give it back as a contribution. This is the manner of OSS.
https://github.com/embedded-software-laboratory/embeddedRTPS/pull/3#issuecomment-944159390

**Comment by ZhenshengLee** [comment]
@takasehideki 

see progress of akampmann  work in https://github.com/embedded-software-laboratory/embeddedRTPS-STM32/issues/12#issuecomment-1103885684_

**Comment by takasehideki** [comment]
Hi @ZhenshengLee thanks to notify me about #12 
I confirmed [feature/track_latest](https://github.com/embedded-software-laboratory/embeddedRTPS-STM32/tree/feature/track_latest) worked well on my environment. So I decide to close this issue!
