### ISSUE TITLE
Bing failed and eth connection

### ISSUE THREAD

**Issue by AhmedElghaly** [embedded-software-laboratory/embeddedRTPS-STM32#13]
Thanks for all authors! But I just has some problems while using ertps-stm32f767zi.
Here is the issue:
Bing is failed and there is no rtps packets in wireshark
I did the same instructions here: https://github.com/embedded-software-laboratory/embeddedRTPS-STM32.git
but the connection still not working and this is the result:
Creating RTPS Participant...
Creating Participant...
Created Participant succesfully.
Creating RTPS reader on topic:TOLINUX
Creating FastRTPS Writer on topic TOSTM
Successfully created writer.
Waiting for reader match with STM32...
So please if you can help, I will be grateful for you.

**Comment by akampmann** [comment]
Hey, please give this branch a try, sorry haven't merged to master yet:

https://github.com/embedded-software-laboratory/embeddedRTPS-STM32/tree/feature/track_latest

**Comment by AhmedElghaly** [comment]
Hi [akampmann],
thanks for reply.
I tried it, but it's downloading without embeddedRTPS library, and tried to clone it to thirdparty folder but I got all of these errors:
Description	Resource	Path	Location	Type
'MAX_NUM_READER_CALLBACKS' is not a member of 'rtps::Config'	Reader.h	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/include/rtps/entities	line 135	C/C++ Problem
'xSemaphoreCreateRecursiveMutex' was not declared in this scope	Lock.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/utils	line 6	C/C++ Problem
'xSemaphoreGiveRecursive' was not declared in this scope	Lock.h	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/include/rtps/utils	line 39	C/C++ Problem
'xSemaphoreTakeRecursive' was not declared in this scope	Lock.h	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/include/rtps/utils	line 36	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 13	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 14	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 43	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 44	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 78	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 79	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 80	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 81	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 83	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 95	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 96	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 97	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/discovery/subdir.mk:28: Middlewares/Third_Party/embeddedRTPS/src/discovery/ParticipantProxyData.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/Domain.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/Participant.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/Reader.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/StatelessReader.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/Writer.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/messages/subdir.mk:22: Middlewares/Third_Party/embeddedRTPS/src/messages/MessageReceiver.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/utils/subdir.mk:19: Middlewares/Third_Party/embeddedRTPS/src/utils/Lock.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** Waiting for unfinished jobs....	embedded_rtps_stm32		 	C/C++ Problem
request for member 'fill' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 8	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 12	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 42	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 73	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 77	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 94	C/C++ Problem
template argument 2 is invalid	Reader.h	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/include/rtps/entities	line 135	C/C++ Problem

So, is there any way to avoid these errors?

**Comment by akampmann** [comment]
I haven't tested some of the recent changes on the STM32, which seem to cause problems.

Please checkout this branch for the embeddedRTPS submodule: https://github.com/embedded-software-laboratory/embeddedRTPS/tree/hotfix/consistent_mutex_usage

Also please pull this repo, as I've added the missing config parameter. I am able to ping the STM32 and I see RTPS packages coming out of it.

If you keep having issues then please use embeddedRTPS @ 1410a87 and not the latest master.

**Comment by AhmedElghaly** [comment]
I did that and the lock.h errors has gone, but the reader.h and reader.cpp still has some errors:
Description	Resource	Path	Location	Type
'MAX_NUM_READER_CALLBACKS' is not a member of 'rtps::Config'	Reader.h	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/include/rtps/entities	line 136	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 13	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 14	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 43	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 44	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 78	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 79	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 80	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 81	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 83	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 95	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 96	C/C++ Problem
invalid types 'int[unsigned int]' for array subscript	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 97	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/discovery/subdir.mk:28: Middlewares/Third_Party/embeddedRTPS/src/discovery/ParticipantProxyData.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/Domain.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/Participant.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/Reader.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/entities/subdir.mk:31: Middlewares/Third_Party/embeddedRTPS/src/entities/StatelessReader.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** [Middlewares/Third_Party/embeddedRTPS/src/messages/subdir.mk:22: Middlewares/Third_Party/embeddedRTPS/src/messages/MessageReceiver.o] Error 1	embedded_rtps_stm32		 	C/C++ Problem
make: *** Waiting for unfinished jobs....	embedded_rtps_stm32		 	C/C++ Problem
request for member 'fill' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 8	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 12	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 42	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 73	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 77	C/C++ Problem
request for member 'size' in '((rtps::Reader*)this)->rtps::Reader::m_callbacks', which is of non-class type 'int'	Reader.cpp	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/src/entities	line 94	C/C++ Problem
template argument 2 is invalid	Reader.h	/embedded_rtps_stm32/Middlewares/Third_Party/embeddedRTPS/include/rtps/entities	line 136	C/C++ Problem

**Comment by akampmann** [comment]
Please pull https://github.com/embedded-software-laboratory/embeddedRTPS-STM32/tree/feature/track_latest

This file contains the missing config parameter: https://github.com/embedded-software-laboratory/embeddedRTPS-STM32/blob/feature/track_latest/stm32/Core/Inc/rtps/config.h

**Comment by AhmedElghaly** [comment]
I'm already using this https://github.com/embedded-software-laboratory/embeddedRTPS-STM32/tree/feature/track_latest but got the errors that I sent above.
Please, can you send the working project files on my email?
if it's ok, just send it to: ahmedsaad.2feb@gmail.com

**Comment by akampmann** [comment]
You are either using the wrong config.h or haven't pulled.

As the error indicates, the following parameter is missing in your config.h:

const uint8_t MAX_NUM_READER_CALLBACKS = 5;

 Add it to your config and it should compile.

**Comment by AhmedElghaly** [comment]
Thank you so much, Now it's compiling.
but while trying to connect it with linux still getting this:
Creating RTPS Participant...
Creating Participant...
Created Participant succesfully.
Creating RTPS reader on topic:TOLINUX
Creating FastRTPS Writer on topic TOSTM
Successfully created writer.
Waiting for reader match with STM32...
[output_file.zip](https://github.com/embedded-software-laboratory/embeddedRTPS-STM32/files/9454430/output_file.zip)

**Comment by AhmedElghaly** [comment]
Also, which version for linux fast dds that I have to use?

**Comment by akampmann** [comment]
Your Linux machine is on a different subnet (192.168.0.1) than the STM (192.168.1.103). Please change the IP Address of your Linux machine to be in the same 192.168.1.* subnet.

I've tried it with the FastDDS commit that is included as a submodule in this repo.

**Comment by akampmann** [comment]
@AhmedElghaly can I close this issue?

**Comment by AhmedElghaly** [comment]
Yes, thank you so much for your help.

**Comment by akampmann** [comment]
No problem, hope everything works now.
