### ISSUE TITLE
Does it work through docker/wsl2?

### ISSUE THREAD

**Issue by amcolex** [embedded-software-laboratory/embeddedRTPS-STM32#18]
First of all, thanks @akampmann for sharing this amazing project. 

I'm trying to get this demo running. I managed to build and run it on the STM32 Nucleo just fine.

I also managed to build it on ubuntu 22.04 using WSL2. The network connection seems fine. i.e. i can ping the STM32 (192.168.1.103) just from both the host computer and within WSL.

However, when running the hello_world program, nothing happens.

I did a Wireshark dump, and i get the INFO_TS packets from the Nucleo board, but nothing seems to happen on the Linux side. here is the raw dump: https://www.dropbox.com/scl/fi/f7jpbl3eacsgv946y5zxm/rtps_nucleo_ubuntu_wsl.pcapng?rlkey=bs5fwsgtxa5ed9ukdq29qhyip&dl=0

Do you know of any limitations when running from within a container?

**Comment by amcolex** [comment]
Closing this issue as indeed the multicasting between wsl/docker and the windows host doesn't work. Switched to working with a linux host.

**Comment by akampmann** [comment]
Hi @amcolex thank you for your interest in this project. I never really used it across WSL and Docker - is the limitation inherent to WSL, or can it be fixed through appropriate configuration?

BTW I've sent you an invite on LinkedIn, would love to exchange a few thoughts via DM.
