### ISSUE TITLE
Are there plans to support Serial communication?

### ISSUE THREAD

**Issue by peapodss** [embedded-software-laboratory/embeddedRTPS-STM32#2]
It is great to find that the author has developed this DDS application project for embedded MCU，Is there any plan to add serial communication function to this application?

**Comment by akampmann** [comment]
There currently are no plans to add serial communication. I'm not sure how that would actually work regarding discovery, addressing different participants etc. 

You may want to look into XRCE-DDS, for example here: https://github.com/eProsima/Micro-XRCE-DDS
