### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by takasehideki** [embedded-software-laboratory/embeddedRTPS-STM32#6]
This repository don't have a LICENSE.
Without a copyright license, nobody is legally allowed to use this code. Please choose a license. 

We plan to use the product you have achieved for our R&D activity.
If we may suggest it, the Apache 2.0 license is good choice because this permissive the license that also grant patent rights. And Apache 2.0 prevents you from being able to sue your users over patent infringement claims.

NOTE: also see https://github.com/embedded-software-laboratory/embeddedRTPS/issues/2

**Comment by akampmann** [comment]
Please see my answer here https://github.com/embedded-software-laboratory/embeddedRTPS/issues/2
